# Generated by Django 3.2.7 on 2022-02-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='stripe_customer_id',
            new_name='customer_id',
        ),
    ]
