# Generated by Django 3.2.7 on 2022-02-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_stripe_customer_id_userprofile_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='charge_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
    ]
